#pragma once

#define AGRITECH_WIFI_SSID "CHANGE_ME"
#define AGRITECH_WIFI_PASSWORD "CHANGE_ME"
#define AGRITECH_BACKEND_BASE_URL "http://192.168.1.20:8000"
#define AGRITECH_DEVICE_UID "gateway-001"
#define AGRITECH_DEVICE_SECRET "CHANGE_ME"
#define AGRITECH_HARDWARE_WEBHOOK_SECRET "CHANGE_ME"
