from __future__ import annotations

from .models import CropProfile


DEFAULT_CROP_PROFILES: dict[str, CropProfile] = {
    "tomato": CropProfile(
        crop="tomato",
        plant_type="fruiting",
        base_shelf_life_days=7,
        ideal_temp_min_c=12,
        ideal_temp_max_c=18,
        ideal_humidity_min_pct=85,
        ideal_humidity_max_pct=95,
        temp_sensitivity=0.85,
        humidity_sensitivity=0.6,
        rain_sensitivity=0.45,
    ),
    "spinach": CropProfile(
        crop="spinach",
        plant_type="leafy",
        base_shelf_life_days=3,
        ideal_temp_min_c=0,
        ideal_temp_max_c=5,
        ideal_humidity_min_pct=90,
        ideal_humidity_max_pct=98,
        temp_sensitivity=1.25,
        humidity_sensitivity=1.05,
        rain_sensitivity=0.8,
        damage_sensitivity=1.2,
    ),
    "okra": CropProfile(
        crop="okra",
        plant_type="fruiting",
        base_shelf_life_days=5,
        ideal_temp_min_c=7,
        ideal_temp_max_c=10,
        ideal_humidity_min_pct=90,
        ideal_humidity_max_pct=95,
        temp_sensitivity=0.9,
        humidity_sensitivity=0.7,
        rain_sensitivity=0.45,
    ),
    "onion": CropProfile(
        crop="onion",
        plant_type="bulb",
        base_shelf_life_days=45,
        ideal_temp_min_c=0,
        ideal_temp_max_c=20,
        ideal_humidity_min_pct=55,
        ideal_humidity_max_pct=70,
        temp_sensitivity=0.35,
        humidity_sensitivity=0.65,
        rain_sensitivity=0.55,
    ),
    "potato": CropProfile(
        crop="potato",
        plant_type="tuber",
        base_shelf_life_days=30,
        ideal_temp_min_c=7,
        ideal_temp_max_c=12,
        ideal_humidity_min_pct=85,
        ideal_humidity_max_pct=95,
        temp_sensitivity=0.45,
        humidity_sensitivity=0.45,
        rain_sensitivity=0.3,
    ),
    "mango": CropProfile(
        crop="mango",
        plant_type="fruit",
        base_shelf_life_days=8,
        ideal_temp_min_c=10,
        ideal_temp_max_c=13,
        ideal_humidity_min_pct=85,
        ideal_humidity_max_pct=90,
        temp_sensitivity=0.8,
        humidity_sensitivity=0.55,
        rain_sensitivity=0.35,
    ),
    # ── Indian crops ──────────────────────────────────────────────
    "banana": CropProfile(
        crop="banana",
        plant_type="fruit",
        base_shelf_life_days=7,
        ideal_temp_min_c=13,
        ideal_temp_max_c=15,
        ideal_humidity_min_pct=85,
        ideal_humidity_max_pct=95,
        temp_sensitivity=0.9,
        humidity_sensitivity=0.6,
        rain_sensitivity=0.4,
    ),
    "apple": CropProfile(
        crop="apple",
        plant_type="fruit",
        base_shelf_life_days=30,
        ideal_temp_min_c=0,
        ideal_temp_max_c=5,
        ideal_humidity_min_pct=80,
        ideal_humidity_max_pct=90,
        temp_sensitivity=0.5,
        humidity_sensitivity=0.4,
        rain_sensitivity=0.25,
    ),
    "guava": CropProfile(
        crop="guava",
        plant_type="fruit",
        base_shelf_life_days=5,
        ideal_temp_min_c=10,
        ideal_temp_max_c=15,
        ideal_humidity_min_pct=80,
        ideal_humidity_max_pct=90,
        temp_sensitivity=0.75,
        humidity_sensitivity=0.55,
        rain_sensitivity=0.4,
    ),
    "papaya": CropProfile(
        crop="papaya",
        plant_type="fruit",
        base_shelf_life_days=5,
        ideal_temp_min_c=12,
        ideal_temp_max_c=15,
        ideal_humidity_min_pct=80,
        ideal_humidity_max_pct=90,
        temp_sensitivity=0.85,
        humidity_sensitivity=0.6,
        rain_sensitivity=0.45,
    ),
    "chilli": CropProfile(
        crop="chilli",
        plant_type="fruiting",
        base_shelf_life_days=10,
        ideal_temp_min_c=10,
        ideal_temp_max_c=15,
        ideal_humidity_min_pct=60,
        ideal_humidity_max_pct=75,
        temp_sensitivity=0.6,
        humidity_sensitivity=0.5,
        rain_sensitivity=0.35,
    ),
    "brinjal": CropProfile(
        crop="brinjal",
        plant_type="fruiting",
        base_shelf_life_days=5,
        ideal_temp_min_c=10,
        ideal_temp_max_c=15,
        ideal_humidity_min_pct=85,
        ideal_humidity_max_pct=95,
        temp_sensitivity=0.8,
        humidity_sensitivity=0.6,
        rain_sensitivity=0.4,
    ),
    "cabbage": CropProfile(
        crop="cabbage",
        plant_type="leafy",
        base_shelf_life_days=14,
        ideal_temp_min_c=0,
        ideal_temp_max_c=5,
        ideal_humidity_min_pct=85,
        ideal_humidity_max_pct=95,
        temp_sensitivity=0.55,
        humidity_sensitivity=0.5,
        rain_sensitivity=0.3,
    ),
    "cauliflower": CropProfile(
        crop="cauliflower",
        plant_type="leafy",
        base_shelf_life_days=7,
        ideal_temp_min_c=0,
        ideal_temp_max_c=5,
        ideal_humidity_min_pct=85,
        ideal_humidity_max_pct=95,
        temp_sensitivity=0.7,
        humidity_sensitivity=0.55,
        rain_sensitivity=0.35,
    ),
    "carrot": CropProfile(
        crop="carrot",
        plant_type="root",
        base_shelf_life_days=21,
        ideal_temp_min_c=0,
        ideal_temp_max_c=5,
        ideal_humidity_min_pct=85,
        ideal_humidity_max_pct=95,
        temp_sensitivity=0.4,
        humidity_sensitivity=0.4,
        rain_sensitivity=0.25,
    ),
    "beetroot": CropProfile(
        crop="beetroot",
        plant_type="root",
        base_shelf_life_days=14,
        ideal_temp_min_c=0,
        ideal_temp_max_c=5,
        ideal_humidity_min_pct=85,
        ideal_humidity_max_pct=95,
        temp_sensitivity=0.45,
        humidity_sensitivity=0.45,
        rain_sensitivity=0.3,
    ),
    "green peas": CropProfile(
        crop="green peas",
        plant_type="legume",
        base_shelf_life_days=5,
        ideal_temp_min_c=0,
        ideal_temp_max_c=5,
        ideal_humidity_min_pct=85,
        ideal_humidity_max_pct=95,
        temp_sensitivity=0.9,
        humidity_sensitivity=0.7,
        rain_sensitivity=0.5,
    ),
    "capsicum": CropProfile(
        crop="capsicum",
        plant_type="fruiting",
        base_shelf_life_days=7,
        ideal_temp_min_c=7,
        ideal_temp_max_c=13,
        ideal_humidity_min_pct=85,
        ideal_humidity_max_pct=95,
        temp_sensitivity=0.75,
        humidity_sensitivity=0.6,
        rain_sensitivity=0.4,
    ),
    "bitter_gourd": CropProfile(
        crop="bitter gourd",
        plant_type="fruiting",
        base_shelf_life_days=5,
        ideal_temp_min_c=10,
        ideal_temp_max_c=15,
        ideal_humidity_min_pct=80,
        ideal_humidity_max_pct=90,
        temp_sensitivity=0.8,
        humidity_sensitivity=0.6,
        rain_sensitivity=0.45,
    ),
    "bottle_gourd": CropProfile(
        crop="bottle gourd",
        plant_type="fruiting",
        base_shelf_life_days=5,
        ideal_temp_min_c=10,
        ideal_temp_max_c=15,
        ideal_humidity_min_pct=80,
        ideal_humidity_max_pct=90,
        temp_sensitivity=0.8,
        humidity_sensitivity=0.6,
        rain_sensitivity=0.45,
    ),
    "ridge_gourd": CropProfile(
        crop="ridge gourd",
        plant_type="fruiting",
        base_shelf_life_days=4,
        ideal_temp_min_c=10,
        ideal_temp_max_c=15,
        ideal_humidity_min_pct=80,
        ideal_humidity_max_pct=90,
        temp_sensitivity=0.85,
        humidity_sensitivity=0.65,
        rain_sensitivity=0.5,
    ),
    "drumstick": CropProfile(
        crop="drumstick",
        plant_type="pod",
        base_shelf_life_days=7,
        ideal_temp_min_c=12,
        ideal_temp_max_c=18,
        ideal_humidity_min_pct=60,
        ideal_humidity_max_pct=75,
        temp_sensitivity=0.6,
        humidity_sensitivity=0.5,
        rain_sensitivity=0.35,
    ),
    "fenugreek": CropProfile(
        crop="fenugreek",
        plant_type="leafy",
        base_shelf_life_days=3,
        ideal_temp_min_c=0,
        ideal_temp_max_c=5,
        ideal_humidity_min_pct=85,
        ideal_humidity_max_pct=95,
        temp_sensitivity=1.1,
        humidity_sensitivity=0.9,
        rain_sensitivity=0.7,
        damage_sensitivity=1.1,
    ),
    "coriander": CropProfile(
        crop="coriander",
        plant_type="leafy",
        base_shelf_life_days=3,
        ideal_temp_min_c=0,
        ideal_temp_max_c=5,
        ideal_humidity_min_pct=85,
        ideal_humidity_max_pct=95,
        temp_sensitivity=1.15,
        humidity_sensitivity=0.95,
        rain_sensitivity=0.75,
        damage_sensitivity=1.15,
    ),
    "mint": CropProfile(
        crop="mint",
        plant_type="leafy",
        base_shelf_life_days=4,
        ideal_temp_min_c=0,
        ideal_temp_max_c=5,
        ideal_humidity_min_pct=85,
        ideal_humidity_max_pct=95,
        temp_sensitivity=1.0,
        humidity_sensitivity=0.85,
        rain_sensitivity=0.65,
        damage_sensitivity=1.1,
    ),
    "coconut": CropProfile(
        crop="coconut",
        plant_type="nut",
        base_shelf_life_days=30,
        ideal_temp_min_c=15,
        ideal_temp_max_c=25,
        ideal_humidity_min_pct=60,
        ideal_humidity_max_pct=80,
        temp_sensitivity=0.3,
        humidity_sensitivity=0.3,
        rain_sensitivity=0.2,
    ),
    "areca_nut": CropProfile(
        crop="areca nut",
        plant_type="nut",
        base_shelf_life_days=60,
        ideal_temp_min_c=10,
        ideal_temp_max_c=20,
        ideal_humidity_min_pct=50,
        ideal_humidity_max_pct=70,
        temp_sensitivity=0.25,
        humidity_sensitivity=0.35,
        rain_sensitivity=0.2,
    ),
    "turmeric": CropProfile(
        crop="turmeric",
        plant_type="root",
        base_shelf_life_days=90,
        ideal_temp_min_c=10,
        ideal_temp_max_c=20,
        ideal_humidity_min_pct=50,
        ideal_humidity_max_pct=70,
        temp_sensitivity=0.2,
        humidity_sensitivity=0.3,
        rain_sensitivity=0.15,
    ),
    "ginger": CropProfile(
        crop="ginger",
        plant_type="root",
        base_shelf_life_days=30,
        ideal_temp_min_c=10,
        ideal_temp_max_c=15,
        ideal_humidity_min_pct=80,
        ideal_humidity_max_pct=90,
        temp_sensitivity=0.4,
        humidity_sensitivity=0.45,
        rain_sensitivity=0.3,
    ),
    "groundnut": CropProfile(
        crop="groundnut",
        plant_type="legume",
        base_shelf_life_days=60,
        ideal_temp_min_c=10,
        ideal_temp_max_c=20,
        ideal_humidity_min_pct=40,
        ideal_humidity_max_pct=60,
        temp_sensitivity=0.3,
        humidity_sensitivity=0.4,
        rain_sensitivity=0.2,
    ),
    "soybean": CropProfile(
        crop="soybean",
        plant_type="legume",
        base_shelf_life_days=60,
        ideal_temp_min_c=10,
        ideal_temp_max_c=20,
        ideal_humidity_min_pct=40,
        ideal_humidity_max_pct=60,
        temp_sensitivity=0.3,
        humidity_sensitivity=0.4,
        rain_sensitivity=0.2,
    ),
    "black_gram": CropProfile(
        crop="black gram",
        plant_type="legume",
        base_shelf_life_days=60,
        ideal_temp_min_c=10,
        ideal_temp_max_c=20,
        ideal_humidity_min_pct=40,
        ideal_humidity_max_pct=60,
        temp_sensitivity=0.3,
        humidity_sensitivity=0.4,
        rain_sensitivity=0.2,
    ),
    "green_gram": CropProfile(
        crop="green gram",
        plant_type="legume",
        base_shelf_life_days=60,
        ideal_temp_min_c=10,
        ideal_temp_max_c=20,
        ideal_humidity_min_pct=40,
        ideal_humidity_max_pct=60,
        temp_sensitivity=0.3,
        humidity_sensitivity=0.4,
        rain_sensitivity=0.2,
    ),
    "chickpea": CropProfile(
        crop="chickpea",
        plant_type="legume",
        base_shelf_life_days=90,
        ideal_temp_min_c=10,
        ideal_temp_max_c=20,
        ideal_humidity_min_pct=35,
        ideal_humidity_max_pct=55,
        temp_sensitivity=0.25,
        humidity_sensitivity=0.35,
        rain_sensitivity=0.15,
    ),
    "pigeon_pea": CropProfile(
        crop="pigeon pea",
        plant_type="legume",
        base_shelf_life_days=90,
        ideal_temp_min_c=10,
        ideal_temp_max_c=20,
        ideal_humidity_min_pct=35,
        ideal_humidity_max_pct=55,
        temp_sensitivity=0.25,
        humidity_sensitivity=0.35,
        rain_sensitivity=0.15,
    ),
    "mustard": CropProfile(
        crop="mustard",
        plant_type="seed",
        base_shelf_life_days=120,
        ideal_temp_min_c=10,
        ideal_temp_max_c=20,
        ideal_humidity_min_pct=30,
        ideal_humidity_max_pct=50,
        temp_sensitivity=0.2,
        humidity_sensitivity=0.3,
        rain_sensitivity=0.1,
    ),
    "sunflower": CropProfile(
        crop="sunflower",
        plant_type="seed",
        base_shelf_life_days=60,
        ideal_temp_min_c=10,
        ideal_temp_max_c=20,
        ideal_humidity_min_pct=35,
        ideal_humidity_max_pct=55,
        temp_sensitivity=0.3,
        humidity_sensitivity=0.35,
        rain_sensitivity=0.15,
    ),
    "sugarcane": CropProfile(
        crop="sugarcane",
        plant_type="stalk",
        base_shelf_life_days=14,
        ideal_temp_min_c=15,
        ideal_temp_max_c=25,
        ideal_humidity_min_pct=60,
        ideal_humidity_max_pct=80,
        temp_sensitivity=0.5,
        humidity_sensitivity=0.45,
        rain_sensitivity=0.3,
    ),
    "tea": CropProfile(
        crop="tea",
        plant_type="leaf",
        base_shelf_life_days=3,
        ideal_temp_min_c=0,
        ideal_temp_max_c=5,
        ideal_humidity_min_pct=85,
        ideal_humidity_max_pct=95,
        temp_sensitivity=1.2,
        humidity_sensitivity=1.0,
        rain_sensitivity=0.8,
        damage_sensitivity=1.2,
    ),
    "cashew": CropProfile(
        crop="cashew",
        plant_type="nut",
        base_shelf_life_days=30,
        ideal_temp_min_c=10,
        ideal_temp_max_c=20,
        ideal_humidity_min_pct=40,
        ideal_humidity_max_pct=60,
        temp_sensitivity=0.3,
        humidity_sensitivity=0.35,
        rain_sensitivity=0.2,
    ),
    "rubber": CropProfile(
        crop="rubber",
        plant_type="latex",
        base_shelf_life_days=7,
        ideal_temp_min_c=15,
        ideal_temp_max_c=25,
        ideal_humidity_min_pct=60,
        ideal_humidity_max_pct=80,
        temp_sensitivity=0.5,
        humidity_sensitivity=0.5,
        rain_sensitivity=0.3,
    ),
    "cotton": CropProfile(
        crop="cotton",
        plant_type="fiber",
        base_shelf_life_days=180,
        ideal_temp_min_c=15,
        ideal_temp_max_c=30,
        ideal_humidity_min_pct=30,
        ideal_humidity_max_pct=55,
        temp_sensitivity=0.15,
        humidity_sensitivity=0.25,
        rain_sensitivity=0.1,
    ),
    "jute": CropProfile(
        crop="jute",
        plant_type="fiber",
        base_shelf_life_days=30,
        ideal_temp_min_c=15,
        ideal_temp_max_c=25,
        ideal_humidity_min_pct=60,
        ideal_humidity_max_pct=80,
        temp_sensitivity=0.4,
        humidity_sensitivity=0.45,
        rain_sensitivity=0.3,
    ),
}


def normalize_crop_name(crop: str) -> str:
    return crop.strip().lower().replace("_", " ")


def get_crop_profile(crop: str, profiles: dict[str, CropProfile] | None = None) -> CropProfile:
    profile_map = profiles or DEFAULT_CROP_PROFILES
    key = normalize_crop_name(crop)
    if key not in profile_map:
        raise KeyError(f"No crop profile found for '{crop}'. Add one before running shelf-life logic.")
    return profile_map[key]
